config/routes.rb
Rails.application.routes.draw do

  resources :registrations
  resources :dashboards do
    resources :goals
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  has_many :goals
  has_many :tasks, through: :goals
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :dashboard
  has_many :tasks
  after_initialize :init

  def init
    self.completed = false if self.completed.nil?
    self.pointscurrent ||=0.0
    self.pointsgoal ||= 0.0
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
include DashboardsHelper

  def new
    @dashboard = Dashboard.new
  end

  def show
    @dashboard = Dashboard.find(params[:id])
    @goal = Goal.new
    @goal.dashboard_id = @dashboard_id
  end

  def create
    @dashboard = Dashboard.new(dashboard_params)

    @dashboard.save
    redirect_to dashboard_path(@dashboard)
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
include GoalsHelper
  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.dashboard_id = params[:dashboard_id]
    @goal.save

    redirect_to dashboard_path(@goal.dashboard)
  end

  def index
    @goals = Goal.all
  end

  def show
    @goal =Goal.find(params[:id])
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)

    redirect_to dashboard_path(@goal.dashboard)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

def new
  @registration =Registration.new
end

def create
  @registration = Registration.new(registration_params)

  @registration.save
  redirect_to @registration
end

def show
  @registration = Registration.find(params[:id])
end

def index
  @registrations = Registration.all
end

private
def registration_params
  params.require(:registration).permit(:username, :email)
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper

  def dashboard_params
    params.require(:dashboard).permit(:username)
  end
  
end

app/helpers/goals_helper.rb
module GoalsHelper

  def goal_params
    params.require(:goal).permit(:name)
  end
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboards/new.html.erb
<h1 class='text'> Sample Dashboard </h1>

<h2 class='text'> Create Your Dashboard </h2>

<h3 class='text'> Enter a username </h3>
<%=form_for @dashboard do |f| %>
<p>
<%= f.label :username, "Username", :class => 'text' %>
<%= f.text_field :username %>
</p>
<%= f.submit %>
<% end %>

app/views/dashboards/show.html.erb
<div class='menu'>
<h1 class='text'> Username:
  <%= @dashboard.username %>
</h1>

<% @dashboard.goals.each do |goal| %>
<p class='text'><%= link_to goal.name, dashboard_goal_path(@dashboard,goal), :class => 'text' %></p>
<ul class='text'>
<li class='text'>Completion: <%= goal.completed %></li>
<li class='text'>Points Current:<%= goal.pointscurrent %></li>
<li class='text'>Points Goal:<%= goal.pointsgoal %></li>
<li class='text'>Created At: <%= goal.created_at %></li>
</ul>

<% end %>

<%= render partial: 'goals/form' %>
</div>

app/views/goals/_form.html.erb
<h3 class='text'> Create a Goal </h3>
<%= form_for [@dashboard, @goal] do |f| %>
<p>
<%= f.label :name, "Goal Name", :class => 'text' %><br/>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :completed, :class => 'text' %>
<%= f.check_box :completed%>
</p>

<p>
<%= f.submit 'Submit' %>
</p>
<% end %>

app/views/goals/new.html.erb
<h1> new goal </h1>

app/views/goals/show.html.erb
<%= link_to 'Return to Dashboard', dashboard_path(@goal.dashboard_id), :class => 'text' %>
<h3 class='text'> Goal Name: <%=@goal.name %></h3>
<ul class='text'>
<li class='text'>Completion: <%= @goal.completed %></li>
<li class='text'>Points Current: <%= @goal.pointscurrent %></li>
<li class='text'>Points Goal: <%= @goal.pointsgoal %></li>
<li class='text'>Created At: <%= @goal.created_at %></li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboardio -- The best way to track your goals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<header class='nav'>
  <div class='navcontainer'>
    <div class ='nav' id='home'>Home</div>
    <div class='nav'>About</div>
    <div class ='nav' id='contact'>Contact</div>
    <div class='nav'><%= link_to 'Trial Build', new_dashboard_path%></div>
    <div class='nav' id='login'>Log In</div>
    <div class = 'nav' id='signup'><%= link_to 'Sign Up', new_registration_path, :class =>'nav'%></div>
  </div>
</header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for [@goal, @task] do |f| %>
<p>
  <%= f.label :taskname %> <br>
  <%= f.text_field :taskname %>
</p>
<p>
  <%= f.label :completed %> <br>
  <%= f.check_box :completed %>
</p>
<p>
  <%= f.label :description %> <br>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.label :points %> <br>
  <%= f.number_field :points %>
</p>
<p>
<%= f.submit 'Submit' %>
</p>
<% end %>

app/views/welcome/index.html.erb
<html>
  <body>
  <center>
  <h1 class='text'> Dashboard.io -- Your personal dashboard</h1>
</center>
</body>

</html>